name: medlog
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# all versions with major := 1 are development versions. breaking changes are always expected
version: 1.0.3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  logging: ^1.0.2
  logging_to_logcat: ^0.0.4
  package_info_plus: 1.3.0
  path_provider: ^2.0.7
  shared_preferences: ^2.0.8
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  file: ^6.1.2
  flutter_lints: ^1.0.4
  given_when_then_unit_test: ^0.0.4
  json_serializable: ^6.1.1
  mocktail: 0.2.0
  tuple: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
