name: build-artifacts

on:
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    - run: flutter pub get
    #- run: flutter format --set-exit-if-changed .
    #- run: flutter analyze .
    #- run: flutter test
    - run: flutter build apk
    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName
      # ${{ steps.tagName.outputs.tag }}
    - run: echo ${{ steps.tagName.outputs.tag }}
    - name: rename     
      run: |
        mv build/app/outputs/apk/release/app-release.apk app-release.apk
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: medlog.apk
        path: app-release.apk 
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: ${{ steps.tagName.outputs.tag }} != ''
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
            app-release.apk
