name: CI-Test

on:
  push:
    branches:
      - main, dev
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter pub get
      #- run: flutter format --set-exit-if-changed .
      #- run: flutter analyze .
      
      - run: flutter test
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: reports/test-results.json
          
      # generate via cat medlog.keystore | base64 > keystore_base64
      - name: Configure Keystore for Android
        run: |
          echo "$BASE64_KEYSTORE" | base64 --decode > app/medlog.keystore
          echo "storeFile=medlog.keystore" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android
      - run: flutter build apk --verbose
      - name: rename
        run: |
          mv build/app/outputs/apk/release/app-release.apk app-release.apk
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: medlog.apk
          path: app-release.apk
