name: Test and build

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Flutter version
        run: flutter --version
      - name: Setup dependencies
        run: flutter pub get
      - name: Generate json code
        run: flutter pub run build_runner build

      #- run: flutter format --set-exit-if-changed .
      #- run: flutter analyze .
      - name: Unit tests
        #run: flutter test --no-pub --no-track-widget-creation --reporter expanded
        run: flutter test --no-pub --no-track-widget-creation

      # generate via cat medlog.keystore | base64 > keystore_base64
      - name: Configure Keystore for Android
        run: |
          echo "$BASE64_KEYSTORE" | base64 --decode > app/medlog.keystore
          echo "storeFile=medlog.keystore" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          echo $BASE64_KEYSTORE
          cat key.properties
        env:
          BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Flutter Tag
        uses: jacopocarlini/action-autotag@2.0.4
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - name: Build
        working-directory: .github/workflows/
        run: make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: medlog-release
          path: |
            build/medlog/*-release.apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: medlog-debug
          path: |
            build/medlog/*-debug.apk
