name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'CI-Test' ]                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.json'                    # Path to test results (inside artifact .zip)
          reporter: flutter-json            # Format of test results
